
import type { Metadata } from "next";
import { Sidebar } from "./dashboard/_components/sidebar";
import { TopBar } from "./dashboard/_components/top-bar";
import { EdgeStoreProvider } from '@/lib/edgestore';
import { getServerSession } from "next-auth";
import { nextAuthOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Nome da barbearia - Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(nextAuthOptions)

  if(!session) redirect('/login/dashboard')

  return (
    <EdgeStoreProvider>
      <div className="flex h-screen">
        <Sidebar />
        <div className="w-full">
          <TopBar />
          <div className="p-5">
              {children}
          </div>
        </div>
      </div>
    </EdgeStoreProvider>
  );
}
