import type { Metadata } from "next";
import { Lato as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/components/providers";

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["100", '300', '400', '700', '900'],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Nome da barbearia - Links",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="h-full">
      <body className={cn(
          "min-h-screen h-full bg-background font-sans antialiased",
          fontSans.variable
        )}>
          <Providers>
            {children}
          </Providers>
          <Toaster />
        </body>
    </html>
  );
}
